// Generated by CoffeeScript 1.7.1
$(function() {
  return $('#tags').tagsInput({
    'width': '800px',
    'interactive': true,
    'defaultText': '',
    'removeWithBackspace': true,
    'minChars': 0,
    'maxChars': 0,
    'placeholderColor': '#666666'
  });
});
