// Generated by CoffeeScript 1.7.1
$(function() {
  var $images, $tags, name;
  $tags = $('#tags');
  $images = $('#images');
  if ($tags[0]) {
    $tags.tagsInput({
      'width': '800px',
      'interactive': true,
      'defaultText': '',
      'removeWithBackspace': true,
      'minChars': 0,
      'maxChars': 0,
      'placeholderColor': '#666666'
    });
  }
  if ($images[0]) {
    name = $('#name').html();
    $images.on('click', 'img', function() {
      return $images.append(this.parentNode);
    });
    $('#get').on('click', function() {
      return $.get("/admin/lights/" + name + "/get", function(imgs) {
        var img;
        return $images.html(((function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = imgs.length; _i < _len; _i++) {
            img = imgs[_i];
            _results.push("<div class='thumb'><img src=http://kweb.qiniudn.com/" + img + "-400x300 alt=" + img + "><div class='del'>x</div></div>");
          }
          return _results;
        })()).join(''));
      });
    });
    return $('#sort').on('click', function() {
      return $.post("/admin/lights/" + name, {
        imgs: $.map($images.find('img'), function(e) {
          return e.alt;
        })
      }, function(rs) {
        return console.log(rs);
      });
    });
  }
});
