// Generated by CoffeeScript 1.8.0
$(function() {
  var $images, $tags, name;
  $tags = $('#tags');
  $images = $('#images');
  if ($tags[0]) {
    $tags.tagsInput({
      'width': '800px',
      'interactive': true,
      'defaultText': '',
      'removeWithBackspace': true,
      'minChars': 0,
      'maxChars': 0,
      'placeholderColor': '#666666'
    });
  }
  if ($images[0]) {
    name = $('#name').html();
    $images.on('click', 'img', function() {
      $images.append(this);
      return console.log(this);
    });
    return $('#get').on('click', function() {
      var imgs;
      imgs = [];
      $images.find('img').each(function() {
        return imgs.push(this.alt);
      });
      return $.get("/admin/lights/" + name + "/sort", {
        imgs: imgs
      }, function(rs) {
        return console.log(rs);
      });
    });
  }
});
