// Generated by CoffeeScript 1.7.1
$(function() {
  $('.slider').slick({
    dots: true
  });
  $('#menu-link').on('click', function() {
    $(this).toggleClass('active');
    $('#head').toggleClass('active');
    return console.log('...');
  });
  return $('#projects').magnificPopup({
    delegate: 'a',
    tLoading: 'Loading image #%curr%...',
    type: 'image',
    gallery: {
      enabled: true,
      navigateByImgClick: true,
      preload: [0, 1]
    },
    image: {
      tError: 'error',
      titleSrc: function(item) {
        return item.el.data('desc');
      }
    }
  });
});
