// Generated by CoffeeScript 1.8.0
$(function() {
  var $mscroll;
  $mscroll = $('#mscroll-list');
  if ($mscroll[0]) {
    return $mscroll.imgScroll({
      loop: !0,
      navItems: !0
    });
  }
});
